### ISSUE TITLE
N00b, and possibly annoying question. 

### ISSUE THREAD

**Issue by anthus1** [HannesMann/OpenRayman#2]
Can you create level models, or view the levels/ assets? It would be cool to poke around. The PC version is identical to the N64 version, right? That's the one I grew up with. 

Thanks!  :)

(A simple "no" will suffice, if this is obviously not possible yet.)

**Comment by HannesMann** [comment]
I'm not working on OpenRayman right now, and reverse-engineering the levels/models is hard and time consuming.
@szymski knows a lot more than me about the Rayman 2 level formats, try asking him in some way.
(also yes, the PC version is mostly identical to the N64 version, except that the PC version has higher resolution textures/models and the original soundtrack)

**Comment by anthus1** [comment]
Thanks very much for your reply. Good pick with your projects.
